name: Copy Home to Root

on:
  push:
    paths:
      - 'Home/index.html'

jobs:
  copy-home:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy /Home/index.html to /
        run: |
          cp Home/index.html index.html

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          git commit -m 'Copy updated Home/index.html to root'
          git push
